-- MySQL Script generated by MySQL Workbench
-- Wed Sep 14 20:07:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Genero` ;

CREATE TABLE IF NOT EXISTS `Genero` (
  `ID_Musica` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Musica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Genero_Musica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Genero_Musica` ;

CREATE TABLE IF NOT EXISTS `Genero_Musica` (
  `ID_Genero` INT NOT NULL,
  `ID_Musica` INT NOT NULL,
  PRIMARY KEY (`ID_Genero`, `ID_Musica`),
  CONSTRAINT `fk_Genero_has_Musica_Genero`
    FOREIGN KEY (`ID_Genero`)
    REFERENCES `Genero` (`ID_Musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Genero_has_Musica_Musica1`
    FOREIGN KEY (`ID_Musica`)
    REFERENCES `Musica` (`ID_Musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Genero_has_Musica_Musica1_idx` ON `Genero_Musica` (`ID_Musica` ASC) VISIBLE;

CREATE INDEX `fk_Genero_has_Musica_Genero_idx` ON `Genero_Musica` (`ID_Genero` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Musica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Musica` ;

CREATE TABLE IF NOT EXISTS `Musica` (
  `ID_Musica` INT NOT NULL AUTO_INCREMENT,
  `Autor` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Musica`, `Autor`),
  CONSTRAINT `fk_Musica_Usuario1`
    FOREIGN KEY (`Autor`)
    REFERENCES `Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Musica_Usuario1_idx` ON `Musica` (`Autor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Musica_Favorita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Musica_Favorita` ;

CREATE TABLE IF NOT EXISTS `Musica_Favorita` (
  `Usuario_Ouvinte` INT NOT NULL,
  `Numero_Musica` INT NOT NULL,
  PRIMARY KEY (`Usuario_Ouvinte`, `Numero_Musica`),
  CONSTRAINT `fk_Usuario_has_Musica_Usuario1`
    FOREIGN KEY (`Usuario_Ouvinte`)
    REFERENCES `Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Musica_Musica1`
    FOREIGN KEY (`Numero_Musica`)
    REFERENCES `Musica` (`ID_Musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Musica_Musica1_idx` ON `Musica_Favorita` (`Numero_Musica` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_has_Musica_Usuario1_idx` ON `Musica_Favorita` (`Usuario_Ouvinte` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Seguidores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Seguidores` ;

CREATE TABLE IF NOT EXISTS `Seguidores` (
  `ID_Seguindo` INT NOT NULL,
  `ID_Seguidor` INT NOT NULL,
  PRIMARY KEY (`ID_Seguidor`, `ID_Seguindo`),
  CONSTRAINT `fk_Seguidores_Usuario1`
    FOREIGN KEY (`ID_Seguidor`)
    REFERENCES `Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `ID_Usuario` INT NOT NULL AUTO_INCREMENT,
  `E-mail` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipo_Cadastro` BINARY(2) NOT NULL,
  PRIMARY KEY (`ID_Usuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `E-mail_UNIQUE` ON `Usuario` (`E-mail` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
